#!/bin/bash

GCP_PROJECT=enel-dac-operations-devops
GKE_CLUSTER_NAME=kubeflow-cluster
GKE_CLUSTER_ZONE=europe-west1-d
GKE_CLUSTER_MACHINE_TYPE=n1-standard-2
GKE_CLUSTER_NETWORK=devops
GKE_CLUSTER_SUBNETWORK=devops-belgium

KSONNET_VERSION=0.13.0
KSONNET_FULL_VERSION=ks_${KSONNET_VERSION}_linux_amd64

KUBEFLOW_VERSION=v0.3.3

GCS_BUCKET_TRAINING01=enel-dac-operations-devops-kftr01
IAM_SA_TRAINING01=kf-cl-tr01-sa
IAM_SA_TRAINING01_EMAIL=${IAM_SA_TRAINING01}@${GCP_PROJECT}.iam.gserviceaccount.com
IAM_SA_KEY_JSON_FILENAME=${IAM_SA_TRAINING01}-key.json
IAM_SA_KEY_JSON_FILEPATH=./05T_code/tensorflow-model/${IAM_SA_KEY_JSON_FILENAME}

DOCKER_VERSION_TAG_TRAINING01=1542467123
GCR_TRAIN_PATH_TRAINING01=eu.gcr.io/${GCP_PROJECT}/kubeflow-training01:${DOCKER_VERSION_TAG_TRAINING01}

